{% set name = "eth-event" %}
{% set version = "1.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eth-event-{{ version }}.tar.gz
  sha256: 1589b583a9b0294f9aba4dedce8077685ced298393872f7f19bbf7d67ed9e49a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - eth-abi >=2.0.0,<3.0.0
    - eth-hash >=0.2.0,<1.0.0
    - eth-utils >=1.2.0,<2.0.0
    - hexbytes >=0.2.0,<1.0.0
    - python >=3.6,<4.0

test:
  imports:
    - eth_event
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/iamdefinitelyahuman/eth-event
  summary: Ethereum event decoder and topic generator
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - spinoch
    - iamdefinitelyahuman
